title: First step into GitHub World
author: Mashaarr
email: maria.shmatkova@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 blablabla
# social links
twitter_username: your-twitter-handle
github_username:  shmatkova.maria@gmail.com

show_excerpts: true # set to false to remove excerpts on the homepage
